os:
  - linux
  - osx

language: c
sudo: required

services:
  - docker

env:
  global:
    secure: "ifQWQnOsau0WZOZI4BfJOdpbCewzrK53Fd1/b0vrtuvdkYMNoJjlLOcOMe3PhLJO49mne9GEYVmYSG3vGf+A5/AiEGFbWxOJtgP5lF74ExLpw7uqROgcbT6rdCPEx3cuzc0I+p8TlBl/uszz/kK1IiIx7trWWj7Dclu5mO5DqEl1H8XBR29845aXDiiuEpsQFurIK9seiMUpfi/GOQRx9e5N0xUuLM9s0nfAls7rcYvPlx1VbLuyDcFbHNuAcwGIyiXHqOZw47JUJbC3Z9zXFJxV9AAJOdS2japuTf/55EhHpmsR4M7ItnJweL3KfZxACjAqUgtm51A6uhCMT1nCBsmQXQ36WEDLSyCiyj2F5f6XbBCJt8p4TgBS4mO6NxuZ61hsBa8p0Kzc6laO9dvkUfxMbYlBTj1sWyQeLp89yfoj+XQGt9dguSgddG4UCySjXX0wGcvh330DEdoZkl8Ck+vHqo8UWnat4pwl080hfxY1qO+/qXtgtFQQhCMrHqaGIP5I2e7cX9VJkjiQiW7qVyuO1ocHC29m1y1nCJUfxXOTA5QmcaU3arS7Pbx4FYUUIM2UAxDTavsE6qvygr/wMVyY0dOxXKs8QsIgTIcjZl9wbf3BrW1YeG6XlHuZ1jF6BSdcj/wf3Ukue4dzFjQPMQj2t4UY3excToYJX4V80rA="

# The Dockerfile that defines the image that for the build environment is
# available at https://github.com/omnia-md/conda-recipes/tree/master/devtools/centos5-build-box
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker pull jchodera/omnia-build-box;
    fi
  # Retrieve conda-build-all
  - wget -O conda-build-all --quiet https://raw.githubusercontent.com/omnia-md/conda-recipes/master/conda-build-all
  - chmod u+x conda-build-all

script:
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then
        export CONDA_BUILD_ALL_FLAGS="--force --upload choderalab";
    else
        export CONDA_BUILD_ALL_FLAGS=" ";
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        echo "Building linux...";
        docker run -e CONDA_BUILD_ALL_FLAGS -e BINSTAR_TOKEN -e TRAVIS_PULL_REQUEST
            -t -i --rm -v `pwd`:/io jchodera/omnia-build-box:latest
            bash /io/devtools/docker-build.sh;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        echo "Building osx...";
        bash devtools/osx-build.sh;
    fi
