package:
  name: targetexplorer
  version: !!str 0.1

source:
  git_url: https://github.com/choderalab/TargetExplorer
  git_tag: v0.1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - biopython
    - flask
    - sqlalchemy
    - flask-sqlalchemy
    - pandas
    # - numpy
    - lxml
    - pyyaml

test:
  requires:
    - nose
  imports:
    - targetexplorer

about:
  home: https://github.com/choderalab/targetexplorer
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: Database framework with RESTful API for aggregating genomic, structural, and functional data for target protein families.
